name: Build MacOS

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-macos.yml'
      - 'src/**'
      - 'include/**'
      - 'example/**'
      - 'CMakeLists.txt'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Update CMake
        run: brew install cmake

      - name: Download ONNX Runtime
        run: |
          if [ "${{ matrix.arch }}" == "x86_64" ]; then
            wget https://github.com/microsoft/onnxruntime/releases/download/v1.18.1/onnxruntime-osx-x86_64-1.18.1.tgz -O onnxruntime.tgz
          else
            wget https://github.com/microsoft/onnxruntime/releases/download/v1.18.1/onnxruntime-osx-arm64-1.18.1.tgz -O onnxruntime.tgz
          fi
          mkdir -p onnxruntime
          tar -xzf onnxruntime.tgz -C onnxruntime --strip-components 1
          mkdir -p lib
          rsync -a onnxruntime/lib/ lib/

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} -DONNXRUNTIME_DIR=${PWD}/onnxruntime

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.arch }}
          path: build/

  create-universal-dylibs:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download x86_64 Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-x86_64
          path: build-x86_64

      - name: Download arm64 Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-arm64
          path: build-arm64

      - name: Create Universal dylibs
        run: |
          mkdir -p universal/lib
          for dylib in build-x86_64/lib/*.dylib; do
            dylib_name=$(basename $dylib)
            lipo -create build-x86_64/lib/$dylib_name build-arm64/lib/$dylib_name -output universal/lib/$dylib_name
          done

      - name: Upload Universal dylibs
        uses: actions/upload-artifact@v3
        with:
          name: universal-dylibs
          path: universal/lib/
