name: Build Windows

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-windows.yml'
      - 'src/**'
      - 'include/**'
      - 'example/**'
      - 'CMakeLists.txt'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install CMake
        run: choco install -y cmake

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -- /m:4

      - name: Print Directory Structure
        run: tree

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64
          path: |
            lib/
            include/
